services:
  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/student/data/portainer:/data
    ports:
      - 9000:9000
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
